# Generated by Django 2.0.5 on 2018-08-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=None, max_length=64, unique=True)),
                ('client_secret', models.CharField(default=None, max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=64)),
                ('manager', models.CharField(blank=True, default='', max_length=64)),
                ('info', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, default=None, max_length=64)),
                ('version', models.CharField(db_index=True, default=None, max_length=64)),
                ('report', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='serverlist.Client')),
            ],
        ),
        migrations.CreateModel(
            name='UnknownReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=None, max_length=64)),
                ('client_secret', models.CharField(default=None, max_length=64)),
                ('ip', models.CharField(db_index=True, default=None, max_length=64)),
                ('version', models.CharField(db_index=True, default=None, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
