# Generated by Django 2.0.8 on 2018-09-02 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='vpn_username',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
