# Generated by Django 2.0.9 on 2018-11-16 10:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0005_auto_20180903_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='nt_password_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_updated_at',
            field=models.DateTimeField(default='2018-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shadow_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_number',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
