# Generated by Django 2.0.9 on 2018-11-25 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0006_auto_20181116_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0)),
        ),
    ]
