# Generated by Django 2.0.9 on 2018-12-11 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0007_auto_20181125_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serverlist.Client'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
