# Generated by Django 2.0.9 on 2019-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0008_auto_20181211_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreport',
            name='dns_success',
            field=models.NullBooleanField(default=None),
        ),
    ]
