# Generated by Django 2.0.13 on 2019-06-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverlist', '0009_clientreport_dns_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtpPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, db_index=True, default=None, max_length=255)),
                ('isdir', models.BooleanField(db_index=True, default=None)),
                ('permission', models.CharField(choices=[('none', 'none'), ('read', 'read'), ('write', 'write'), ('admin', 'admin')], db_index=True, default=None, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ftpperm',
            unique_together={('user', 'path')},
        ),
    ]
