# Generated by Django 2.0.13 on 2019-10-08 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0011_employee_ftp_insecure'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vpn_privileged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='vpn_privileged_until',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
