# Generated by Django 2.0.13 on 2020-09-16 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0013_auto_20191126_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='can_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password_updated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
