# Generated by Django 2.0.13 on 2020-09-26 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0014_auto_20200916_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='priority',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
    ]
